### ISSUE TITLE
TypeError: 'NoneType' object is not iterable (Part I)

### ISSUE THREAD

**Issue by mduccc** [galenballew/SDC-Lane-and-Vehicle-Detection-Tracking#5]
I got an error after I had run command `python3 still_image_processing.py`

> Traceback (most recent call last):
>   File "still_image_processing.py", line 151, in <module>
>     processed = process_frame(image)
>   File "still_image_processing.py", line 144, in process_frame
>     line_image = hough_lines(roi_image, rho, theta, threshold, min_line_len, max_line_gap)
>   File "still_image_processing.py", line 84, in hough_lines
>     draw_lines(line_img, lines)
>   File "still_image_processing.py", line 72, in draw_lines
>     for line in lines:
> TypeError: 'NoneType' object is not iterable

**Comment by mduccc** [comment]
`lines = cv2.HoughLinesP(img, rho, theta, threshold, np.array([]), minLineLength=min_line_len, maxLineGap=max_line_gap)` in function `hough_lines` returned `None` at step 2 in for loop
